# Generated by Django 4.2.5 on 2024-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200, null=True)),
                ('task_date', models.DateField()),
                ('task_time', models.TimeField()),
                ('assigned_by', models.CharField(max_length=200, null=True)),
                ('task_status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
