# Generated by Django 4.2.5 on 2024-05-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsatech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Working', 'Working'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
